Don's edits
sqreen/DevelopersSecurityBestPractices pull request #1
Opened 2017-03-29 15:52 UTC by DEGoodmanWilson

I have edited these two articles for grammar. I have some additional thoughts on the presentation of the ideas which I have tried _not_ to do anything with in this PR, as they are better handled via talking about it ;)

2017-03-30 10:00 UTC, Lothiraldan requested changes
Thank you for the PR, I have two / three small comments

2017-03-30 10:00 UTC, Lothiraldan commented on _practices/safe-password-storage/python.md
> +from hashlib import MD5
Here, it's python code and there is no MD5 function in hashlib module

2017-03-30 10:00 UTC, Lothiraldan commented on _practices/safe-password-storage/python.md
> +    return MD5(password)
Same here, please revert

2017-03-30 10:00 UTC, Lothiraldan commented on _practices/safe-password-storage/python.md
> +The problem with brute-forcing passwords is that you need to have a list of "known" passwords in the first place. It's called a `wordlist` and is basically a clear-text file of passwords found in pre
typo here: thatas

2017-03-30 15:00 UTC, DEGoodmanWilson commented on _practices/safe-password-storage/python.md
> +The problem with brute-forcing passwords is that you need to have a list of "known" passwords in the first place. It's called a `wordlist` and is basically a clear-text file of passwords found in pre
Excellent! Addressed.

2017-03-30 15:00 UTC, DEGoodmanWilson commented on _practices/safe-password-storage/python.md
> +from hashlib import MD5
Addressed

2017-03-30 15:00 UTC, DEGoodmanWilson commented on _practices/safe-password-storage/python.md
> +    return MD5(password)
Addressed

2017-04-10 08:11 UTC, Lothiraldan approved these changes

2017-04-10 08:11 UTC, Lothiraldan commented
Thank you @DEGoodmanWilson for your contribution!

2017-04-10 08:12 UTC, merged